export const DEVICE_REPOSITORY = Symbol("DEVICE_REPOSITORY");
export const CREATE_DEVICE_USE_CASE = Symbol("CREATE_DEVICE_USE_CASE");
export const APP_DATASOURCE = Symbol("APP_DATASOURCE");
export const DEVICE_CONTROLLER = Symbol("DEVICE_CONTROLLER");
